version: '3.2'

services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.1
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - 9200:9200
  gen_api:
    build:
      context: ./api
      dockerfile: ./dockerfiles/api/Dockerfile
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - "elasticsearch"
    stdin_open: true
    tty: true
  hack-nginx:
    image: nginx:mainline-alpine
    container_name: hack-nginx
    ports:
      - "4080:4080"
      - "4443:4443"
      - "1489:1489"
    volumes:
      - ./nginx:/etc/nginx
    restart: always
